import type { Metadata } from "next"
import { Geist, Geist_Mono, IBM_Plex_Sans_Condensed } from "next/font/google"
import "./globals.css"
import { Navbar } from "../components/landingPart"
import Providers from "../components/Providers"
import LenisProvider from "../utils/lenis"

const ibmPlexSansCondensed = IBM_Plex_Sans_Condensed({
  variable: "--font-ibm-plex-sans-condensed",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={` ${ibmPlexSansCondensed.variable} antialiased `}>
        <Providers>
          <LenisProvider>{children}</LenisProvider>
        </Providers>
      </body>
    </html>
  )
}
