import type { Metadata } from "next";
import { Geist, Geist_Mono, Dancing_Script } from "next/font/google";
import "./globals.css";
import { Navbar } from "../components/landingPart";
import Providers from "../components/Providers";
import LenisProvider from "../utils/lenis";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const dancingScript = Dancing_Script({
  subsets: ["latin", "vietnamese"], // cần cho tiếng Việt
  weight: ["400", "500", "600", "700"], // đúng các weight bạn sẽ dùng
  variable: "--font-dancing-script",
  style: ["normal"], // thêm "italic" nếu bạn dùng nghiêng
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Providers>
          <LenisProvider>{children}</LenisProvider>
        </Providers>
      </body>
    </html>
  );
}
